// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.7.0 (commit 02c67d121b0d08478eaf3512f479e7a326d39940).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { CheckUserPaidByPocketOptionId } from "./check_user_paid_by_pocket_option_id_reducer.ts";
export { CheckUserPaidByPocketOptionId };
import { LoginWithPocketOptionId } from "./login_with_pocket_option_id_reducer.ts";
export { LoginWithPocketOptionId };
import { MarkUserPaidByPocketOptionId } from "./mark_user_paid_by_pocket_option_id_reducer.ts";
export { MarkUserPaidByPocketOptionId };
import { RegisterUser } from "./register_user_reducer.ts";
export { RegisterUser };

// Import and reexport all table handle types
import { UserPaymentTableHandle } from "./user_payment_table.ts";
export { UserPaymentTableHandle };

// Import and reexport all types
import { UserPayment } from "./user_payment_type.ts";
export { UserPayment };

const REMOTE_MODULE = {
  tables: {
    user_payment: {
      tableName: "user_payment" as const,
      rowType: UserPayment.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
      primaryKeyInfo: {
        colName: "identity",
        colType: (UserPayment.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    check_user_paid_by_pocket_option_id: {
      reducerName: "check_user_paid_by_pocket_option_id",
      argsType: CheckUserPaidByPocketOptionId.getTypeScriptAlgebraicType(),
    },
    login_with_pocket_option_id: {
      reducerName: "login_with_pocket_option_id",
      argsType: LoginWithPocketOptionId.getTypeScriptAlgebraicType(),
    },
    mark_user_paid_by_pocket_option_id: {
      reducerName: "mark_user_paid_by_pocket_option_id",
      argsType: MarkUserPaidByPocketOptionId.getTypeScriptAlgebraicType(),
    },
    register_user: {
      reducerName: "register_user",
      argsType: RegisterUser.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.7.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CheckUserPaidByPocketOptionId", args: CheckUserPaidByPocketOptionId }
| { name: "LoginWithPocketOptionId", args: LoginWithPocketOptionId }
| { name: "MarkUserPaidByPocketOptionId", args: MarkUserPaidByPocketOptionId }
| { name: "RegisterUser", args: RegisterUser }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  checkUserPaidByPocketOptionId(pocketOptionId: string) {
    const __args = { pocketOptionId };
    let __writer = new __BinaryWriter(1024);
    CheckUserPaidByPocketOptionId.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("check_user_paid_by_pocket_option_id", __argsBuffer, this.setCallReducerFlags.checkUserPaidByPocketOptionIdFlags);
  }

  onCheckUserPaidByPocketOptionId(callback: (ctx: ReducerEventContext, pocketOptionId: string) => void) {
    this.connection.onReducer("check_user_paid_by_pocket_option_id", callback);
  }

  removeOnCheckUserPaidByPocketOptionId(callback: (ctx: ReducerEventContext, pocketOptionId: string) => void) {
    this.connection.offReducer("check_user_paid_by_pocket_option_id", callback);
  }

  loginWithPocketOptionId(pocketOptionId: string) {
    const __args = { pocketOptionId };
    let __writer = new __BinaryWriter(1024);
    LoginWithPocketOptionId.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("login_with_pocket_option_id", __argsBuffer, this.setCallReducerFlags.loginWithPocketOptionIdFlags);
  }

  onLoginWithPocketOptionId(callback: (ctx: ReducerEventContext, pocketOptionId: string) => void) {
    this.connection.onReducer("login_with_pocket_option_id", callback);
  }

  removeOnLoginWithPocketOptionId(callback: (ctx: ReducerEventContext, pocketOptionId: string) => void) {
    this.connection.offReducer("login_with_pocket_option_id", callback);
  }

  markUserPaidByPocketOptionId(pocketOptionId: string, paymentReference: string, paymentAmount: bigint, paymentTimestamp: __Timestamp) {
    const __args = { pocketOptionId, paymentReference, paymentAmount, paymentTimestamp };
    let __writer = new __BinaryWriter(1024);
    MarkUserPaidByPocketOptionId.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("mark_user_paid_by_pocket_option_id", __argsBuffer, this.setCallReducerFlags.markUserPaidByPocketOptionIdFlags);
  }

  onMarkUserPaidByPocketOptionId(callback: (ctx: ReducerEventContext, pocketOptionId: string, paymentReference: string, paymentAmount: bigint, paymentTimestamp: __Timestamp) => void) {
    this.connection.onReducer("mark_user_paid_by_pocket_option_id", callback);
  }

  removeOnMarkUserPaidByPocketOptionId(callback: (ctx: ReducerEventContext, pocketOptionId: string, paymentReference: string, paymentAmount: bigint, paymentTimestamp: __Timestamp) => void) {
    this.connection.offReducer("mark_user_paid_by_pocket_option_id", callback);
  }

  registerUser(pocketOptionId: string) {
    const __args = { pocketOptionId };
    let __writer = new __BinaryWriter(1024);
    RegisterUser.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("register_user", __argsBuffer, this.setCallReducerFlags.registerUserFlags);
  }

  onRegisterUser(callback: (ctx: ReducerEventContext, pocketOptionId: string) => void) {
    this.connection.onReducer("register_user", callback);
  }

  removeOnRegisterUser(callback: (ctx: ReducerEventContext, pocketOptionId: string) => void) {
    this.connection.offReducer("register_user", callback);
  }

}

export class SetReducerFlags {
  checkUserPaidByPocketOptionIdFlags: __CallReducerFlags = 'FullUpdate';
  checkUserPaidByPocketOptionId(flags: __CallReducerFlags) {
    this.checkUserPaidByPocketOptionIdFlags = flags;
  }

  loginWithPocketOptionIdFlags: __CallReducerFlags = 'FullUpdate';
  loginWithPocketOptionId(flags: __CallReducerFlags) {
    this.loginWithPocketOptionIdFlags = flags;
  }

  markUserPaidByPocketOptionIdFlags: __CallReducerFlags = 'FullUpdate';
  markUserPaidByPocketOptionId(flags: __CallReducerFlags) {
    this.markUserPaidByPocketOptionIdFlags = flags;
  }

  registerUserFlags: __CallReducerFlags = 'FullUpdate';
  registerUser(flags: __CallReducerFlags) {
    this.registerUserFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get userPayment(): UserPaymentTableHandle<'user_payment'> {
    // clientCache is a private property
    return new UserPaymentTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<UserPayment>(REMOTE_MODULE.tables.user_payment));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
